/*
 * Integration Test Runner for KMA Assembler
 *
 * This test runner performs end-to-end testing of the assembler by:
 * 1. Converting human-readable hex files (plain/*.hex) to binary
 * (expected/*.kmx)
 * 2. Running the assembler on source files (source/*.kas) to produce output
 * (target/*.kmx)
 * 3. Comparing the assembler output against expected output
 *
 * Directory structure:
 *   tests/plain/     - Human-readable hex representation of expected output
 *   tests/expected/  - Binary files converted from plain/ (generated by this
 * tool) tests/source/    - Assembly source files (.kas) tests/target/    -
 * Assembler output files (generated by assembler)
 */

#include <ctype.h>
#include <dirent.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <unistd.h>

/* Configuration constants */
#define MAX_PATH 512
#define MAX_FILENAME 256
#define BUFFER_SIZE 4096

/* Directory paths */
#define DIR_PLAIN "plain"
#define DIR_EXPECTED "expected"
#define DIR_SOURCE "source"
#define DIR_TARGET "target"
#define ASSEMBLER_PATH "../kmas.exe"

/* Test statistics */
struct TestStats {
  int total_tests;
  int passed;
  int failed;
  int conversion_errors;
  int assembler_errors;
  int comparison_errors;
};

/* Function declarations */
static int convert_hex_to_binary(const char *hex_file, const char *bin_file);
static int run_assembler(const char *source_file, const char *target_file);
static int compare_binary_files(const char *file1, const char *file2);
static int ensure_directory_exists(const char *path);
static int get_base_name(const char *filename, char *basename, size_t len);
static void print_test_summary(struct TestStats *stats);
static int hex_char_to_value(char c);
static int is_hex_file(const char *filename);
static int is_kas_file(const char *filename);

/**
 * Main test runner entry point.
 * Orchestrates the entire testing process:
 * 1. Converts hex files to binary expected outputs
 * 2. Runs assembler on all source files
 * 3. Compares outputs and reports results
 */
int main(void) {
  struct TestStats stats = {0};
  DIR *dir = NULL;
  struct dirent *entry = NULL;
  char plain_path[MAX_PATH];
  char expected_path[MAX_PATH];
  char source_path[MAX_PATH];
  char target_path[MAX_PATH];
  char basename[MAX_FILENAME];
  int conversion_success = 0;
  int assembly_success = 0;
  int comparison_success = 0;

  printf("==========================================\n");
  printf("KMA Assembler Integration Test Runner\n");
  printf("==========================================\n\n");

  /* Ensure all required directories exist */
  if (!ensure_directory_exists(DIR_EXPECTED) ||
      !ensure_directory_exists(DIR_TARGET)) {
    fprintf(stderr, "Error: Failed to create required directories\n");
    return 1;
  }

  /* Phase 1: Convert all hex files in plain/ to binary in expected/ */
  printf("Phase 1: Converting hex files to binary expectations...\n");
  printf("----------------------------------------------------------\n");

  dir = opendir(DIR_PLAIN);
  if (!dir) {
    fprintf(stderr, "Error: Cannot open directory '%s'\n", DIR_PLAIN);
    fprintf(stderr, "Make sure you're running from project root directory\n");
    return 1;
  }

  while ((entry = readdir(dir)) != NULL) {
    if (!is_hex_file(entry->d_name)) {
      continue;
    }

    /* Build paths for conversion: plain/test.hex -> expected/test.kmx */
    snprintf(plain_path, sizeof(plain_path), "%s/%s", DIR_PLAIN, entry->d_name);

    if (!get_base_name(entry->d_name, basename, sizeof(basename))) {
      fprintf(stderr, "  [ERROR] Invalid filename: %s\n", entry->d_name);
      stats.conversion_errors++;
      continue;
    }

    snprintf(expected_path, sizeof(expected_path), "%s/%s.kmx", DIR_EXPECTED,
             basename);

    printf("  Converting: %s -> %s\n", entry->d_name, basename);

    if (convert_hex_to_binary(plain_path, expected_path)) {
      printf("    [OK] Conversion successful\n");
    } else {
      fprintf(stderr, "    [FAIL] Conversion failed\n");
      stats.conversion_errors++;
    }
  }
  closedir(dir);

  printf("\n");

  /* Phase 2: Run assembler on all source files */
  printf("Phase 2: Running assembler on source files...\n");
  printf("----------------------------------------------------------\n");

  dir = opendir(DIR_SOURCE);
  if (!dir) {
    fprintf(stderr, "Error: Cannot open directory '%s'\n", DIR_SOURCE);
    return 1;
  }

  while ((entry = readdir(dir)) != NULL) {
    if (!is_kas_file(entry->d_name)) {
      continue;
    }

    stats.total_tests++;

    /* Build paths: source/test.kas -> target/test.kmx */
    snprintf(source_path, sizeof(source_path), "%s/%s", DIR_SOURCE,
             entry->d_name);

    if (!get_base_name(entry->d_name, basename, sizeof(basename))) {
      fprintf(stderr, "  [ERROR] Invalid filename: %s\n", entry->d_name);
      stats.failed++;
      continue;
    }

    snprintf(target_path, sizeof(target_path), "%s/%s.kmx", DIR_TARGET,
             basename);
    snprintf(expected_path, sizeof(expected_path), "%s/%s.kmx", DIR_EXPECTED,
             basename);

    printf("\nTest: %s\n", basename);
    printf("  Source: %s\n", entry->d_name);

    /* Run the assembler */
    assembly_success = run_assembler(source_path, target_path);

    if (!assembly_success) {
      fprintf(stderr, "  [FAIL] Assembler failed or crashed\n");
      stats.failed++;
      stats.assembler_errors++;
      continue;
    }

    printf("  [OK] Assembly completed\n");

    /* Compare assembler output with expected output */
    comparison_success = compare_binary_files(target_path, expected_path);

    if (comparison_success == 0) {
      printf("  [PASS] Output matches expected\n");
      stats.passed++;
    } else if (comparison_success == -1) {
      fprintf(stderr, "  [FAIL] Cannot open files for comparison\n");
      stats.failed++;
      stats.comparison_errors++;
    } else {
      fprintf(stderr, "  [FAIL] Output differs from expected\n");
      fprintf(stderr, "        Generated: %s\n", target_path);
      fprintf(stderr, "        Expected:  %s\n", expected_path);
      fprintf(stderr, "        Diff at byte: %d\n", comparison_success - 1);
      stats.failed++;
    }
  }
  closedir(dir);

  /* Print summary */
  printf("\n");
  print_test_summary(&stats);

  return (stats.failed > 0) ? 1 : 0;
}

/**
 * Convert a human-readable hex file to binary format.
 *
 * The hex file should contain hexadecimal digits (0-9, a-f, A-F) with
 * optional whitespace. Each pair of hex digits represents one byte.
 * For example: "4B 4D 58" converts to bytes 0x4B, 0x4D, 0x58
 *
 * Returns 1 on success, 0 on failure.
 */
static int convert_hex_to_binary(const char *hex_file, const char *bin_file) {
  FILE *in = NULL;
  FILE *out = NULL;
  char hex_buffer[BUFFER_SIZE];
  unsigned char byte_buffer[BUFFER_SIZE / 2];
  size_t hex_pos = 0;
  size_t byte_count = 0;
  int c = 0;
  int high_nibble = -1;
  int success = 0;

  in = fopen(hex_file, "r");
  if (!in) {
    fprintf(stderr, "Error: Cannot open hex file '%s'\n", hex_file);
    return 0;
  }

  out = fopen(bin_file, "wb");
  if (!out) {
    fprintf(stderr, "Error: Cannot create binary file '%s'\n", bin_file);
    fclose(in);
    return 0;
  }

  /* Read hex file and convert to binary byte by byte */
  while ((c = fgetc(in)) != EOF) {
    /* Skip whitespace and common separators */
    if (isspace(c) || c == ',' || c == ':' || c == '-') {
      continue;
    }
    if (c == '#') { // skip comments python style
      while (c == '\n') {
        continue;
      }
    }

    /* Check if character is valid hex digit */
    if (!isxdigit(c)) {
      fprintf(stderr, "Error: Invalid hex character '%c' in %s\n", c, hex_file);
      goto cleanup;
    }

    /* Convert hex character to value (0-15) */
    int nibble = hex_char_to_value(c);

    if (high_nibble == -1) {
      /* This is the first nibble (high 4 bits) of a byte */
      high_nibble = nibble;
    } else {
      /* This is the second nibble (low 4 bits), complete the byte */
      byte_buffer[byte_count++] = (high_nibble << 4) | nibble;
      high_nibble = -1;

      /* Flush buffer when it's full */
      if (byte_count >= sizeof(byte_buffer)) {
        if (fwrite(byte_buffer, 1, byte_count, out) != byte_count) {
          fprintf(stderr, "Error: Failed to write to %s\n", bin_file);
          goto cleanup;
        }
        byte_count = 0;
      }
    }
  }

  /* Check if there's an incomplete byte at the end */
  if (high_nibble != -1) {
    fprintf(stderr,
            "Warning: Odd number of hex digits in %s, "
            "last nibble ignored\n",
            hex_file);
  }

  /* Write remaining bytes */
  if (byte_count > 0) {
    if (fwrite(byte_buffer, 1, byte_count, out) != byte_count) {
      fprintf(stderr, "Error: Failed to write final bytes to %s\n", bin_file);
      goto cleanup;
    }
  }

  success = 1;

cleanup:
  if (in)
    fclose(in);
  if (out)
    fclose(out);
  return success;
}

/**
 * Run the assembler on a source file to produce output.
 * Uses fork/exec to run the assembler as a separate process.
 *
 * Returns 1 if assembler ran successfully (exit code 0), 0 otherwise.
 */
static int run_assembler(const char *source_file, const char *target_file) {
  pid_t pid;
  int status;

  pid = fork();

  if (pid == -1) {
    fprintf(stderr, "Error: Failed to fork process\n");
    return 0;
  }

  if (pid == 0) {
    /* Child process: execute the assembler */
    /* Redirect stderr to /dev/null to suppress error messages during testing */
    /* You can comment out the next 3 lines to see assembler errors */
    freopen("/dev/null", "w", stderr);

    execl(ASSEMBLER_PATH, ASSEMBLER_PATH, source_file, target_file, NULL);

    /* If exec returns, it failed */
    fprintf(stderr, "Error: Failed to execute %s\n", ASSEMBLER_PATH);
    exit(1);
  } else {
    /* Parent process: wait for assembler to complete */
    if (waitpid(pid, &status, 0) == -1) {
      fprintf(stderr, "Error: Failed to wait for child process\n");
      return 0;
    }

    /* Check if assembler exited successfully */
    if (WIFEXITED(status)) {
      return WEXITSTATUS(status) == 0;
    }

    return 0;
  }
}

/**
 * Compare two binary files byte by byte.
 *
 * Returns:
 *   0 if files are identical
 *  -1 if files cannot be opened
 *  >0 the position (1-indexed) of the first differing byte
 */
static int compare_binary_files(const char *file1, const char *file2) {
  FILE *f1 = NULL;
  FILE *f2 = NULL;
  unsigned char buf1[BUFFER_SIZE];
  unsigned char buf2[BUFFER_SIZE];
  size_t read1, read2;
  size_t position = 0;
  int result = 0;

  f1 = fopen(file1, "rb");
  f2 = fopen(file2, "rb");

  if (!f1 || !f2) {
    if (f1)
      fclose(f1);
    if (f2)
      fclose(f2);
    return -1;
  }

  /* Compare files in chunks */
  while (1) {
    read1 = fread(buf1, 1, BUFFER_SIZE, f1);
    read2 = fread(buf2, 1, BUFFER_SIZE, f2);

    /* If read sizes differ, files are different */
    if (read1 != read2) {
      result = position + 1;
      break;
    }

    /* If no more data, files are identical */
    if (read1 == 0) {
      result = 0;
      break;
    }

    /* Compare the buffers byte by byte */
    for (size_t i = 0; i < read1; i++) {
      if (buf1[i] != buf2[i]) {
        result = position + i + 1;
        goto cleanup;
      }
    }

    position += read1;
  }

cleanup:
  fclose(f1);
  fclose(f2);
  return result;
}

/**
 * Ensure a directory exists, creating it if necessary.
 * Returns 1 on success, 0 on failure.
 */
static int ensure_directory_exists(const char *path) {
  struct stat st = {0};

  if (stat(path, &st) == -1) {
    /* Directory doesn't exist, try to create it */
    if (mkdir(path, 0755) == -1) {
      fprintf(stderr, "Error: Cannot create directory '%s'\n", path);
      return 0;
    }
    printf("Created directory: %s\n", path);
  }

  return 1;
}

/**
 * Extract the base name from a filename (without extension).
 * For example: "test.kas" -> "test", "example.hex" -> "example"
 *
 * Returns 1 on success, 0 on failure.
 */
static int get_base_name(const char *filename, char *basename, size_t len) {
  const char *dot = NULL;
  size_t copy_len = 0;

  if (!filename || !basename || len == 0) {
    return 0;
  }

  /* Find the last dot in the filename */
  dot = strrchr(filename, '.');

  if (dot) {
    copy_len = dot - filename;
  } else {
    copy_len = strlen(filename);
  }

  /* Ensure we don't overflow the buffer */
  if (copy_len >= len) {
    copy_len = len - 1;
  }

  strncpy(basename, filename, copy_len);
  basename[copy_len] = '\0';

  return 1;
}

/**
 * Print a summary of test results with statistics.
 */
static void print_test_summary(struct TestStats *stats) {
  printf("==========================================\n");
  printf("Test Summary\n");
  printf("==========================================\n");
  printf("Total tests:          %d\n", stats->total_tests);
  printf("Passed:               %d\n", stats->passed);
  printf("Failed:               %d\n", stats->failed);

  if (stats->conversion_errors > 0) {
    printf("Conversion errors:    %d\n", stats->conversion_errors);
  }
  if (stats->assembler_errors > 0) {
    printf("Assembler errors:     %d\n", stats->assembler_errors);
  }
  if (stats->comparison_errors > 0) {
    printf("Comparison errors:    %d\n", stats->comparison_errors);
  }

  printf("\n");

  if (stats->failed == 0 && stats->total_tests > 0) {
    printf("✓ All tests passed!\n");
  } else if (stats->total_tests == 0) {
    printf("⚠ No tests found in %s/\n", DIR_SOURCE);
  } else {
    printf("✗ %d test%s failed\n", stats->failed,
           stats->failed == 1 ? "" : "s");
  }

  printf("==========================================\n");
}

/**
 * Convert a hexadecimal character to its numeric value.
 * Returns value 0-15, or -1 for invalid characters.
 */
static int hex_char_to_value(char c) {
  if (c >= '0' && c <= '9') {
    return c - '0';
  }
  if (c >= 'a' && c <= 'f') {
    return 10 + (c - 'a');
  }
  if (c >= 'A' && c <= 'F') {
    return 10 + (c - 'A');
  }
  return -1;
}

/**
 * Check if a filename has a .hex extension (or similar hex format indicators).
 * Returns 1 if it's a hex file, 0 otherwise.
 */
static int is_hex_file(const char *filename) {
  size_t len = strlen(filename);

  if (len < 5) {
    return 0; /* Too short to have .hex extension */
  }

  /* Check for common hex file extensions */
  return (strcmp(filename + len - 4, ".hex") == 0 ||
          strcmp(filename + len - 4, ".txt") == 0);
}

/**
 * Check if a filename has a .kas extension (KMA assembly source).
 * Returns 1 if it's a KAS file, 0 otherwise.
 */
static int is_kas_file(const char *filename) {
  size_t len = strlen(filename);

  if (len < 5) {
    return 0; /* Too short to have .kas extension */
  }

  return strcmp(filename + len - 4, ".kas") == 0;
}
